language:
  - python

python:
  - 2.7

before_install:
  - sudo apt-get update -qq

install:
  # g++4.8.1
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - ./install.sh

script:
  - $CXX --version
  - ./run_tests.sh
  - ./run_tests_static.sh

